const AppListTypes = {
  FETCH_APP_LISTS_START: 'FETCH_APP_LISTS_START',
  FETCH_APP_LISTS_SUCCESS: 'FETCH_APP_LISTS_SUCCESS',
  FETCH_APP_LISTS_FAILURE: 'FETCH_APP_LISTS_FAILURE',
  FETCH_APP_STATS_START: 'FETCH_APP_STATS_START',
  FETCH_APP_STATS_SUCCESS: 'FETCH_APP_STATS_SUCCESS',
  FETCH_APP_STATS_FAILURE: 'FETCH_APP_STATS_FAILURE',
};

export default AppListTypes;
